---
check:
  - '**/*.html'
ignore:
  # FIXME: we need to improve the HTML check, although aspell supports HTML
  # it's not perfect and in some cases it checks also the embedded JS :-(
  - 'blog/index.html'
  - '_includes/paging.html'
  - '_includes/head.html'
  - '_includes/sharing.html'
  - '_layouts/post.html'
  - '_site/**/*'
  - 'blog/categories.html'
  - 'blog/tags.html'
dictionary:
- abovementioned
- accessor
- AddResolvables
- afterwards
- ALLGLOBAL
- apparmor
- Apparmor
- Args
- aspell
- attr
- auth
- AutoClient
- autoconf
- autoconfiguration
- AutoInst
- autoinstallation
- AutoInstClient
- AutoInstClonable
- AutoInstDataType
- AutoInstMerge
- AutoInstMergeTypes
- AutoInstOptional
- AutoInstPath
- AutoInstRequires
- AutoInstResource
- AutoInstSchema
- autolinking
- AutoLogResource
- automake
- AutoPackages
- AutoSequence
- autotools
- Autotools
- autoyast
- Autoyast
- AutoYaST
- backend
- backport
- backporting
- backtrace
- bcond
- bootloader
- Bootloader
- BootStorage
- br
- break
- breakpoint
- bt
- Btrfs
- bugzilla
- BuildRequires
- Builtins
- byebug
- Byebug
- bz
- cd
- Changelog
- cheatsheet
- checkin
- chroot
- chrooted
- ci
- CIFS
- cim
- CIM
- cio
- CLI
- CloseDialog
- CMake
- cmdline
- conf
- CONF
- config
- CreateDialog
- Ctrl
- CVE
- cvs
- DASD
- datatypes
- dbus
- DBus
- debian
- DEBUGALL
- DEBUGONCRASH
- DEBUGSHELL
- desc
- dev
- Devel
- devtools
- dhcp
- dialogs
- dir
- DISABLELANGUAGEPLUGINS
- dns
- DNS
- docbook
- dpkg
- drbd
- elsif
- endfor
- endif
- EOF
- eval
- Eval
- fcoe
- FCoE
# uppercase FCoE only needed for doctumenting ENVs
- FCOE
- Fibre
- FileSystem
- firstboot
- FIXME
- fontconfig
- FstabDialog
- FTPd
- func
- gcc
- GCC
- gdb
- GDB
- GenericName
- geo
- GetModified
- gettext
- gif
- github
- Github
- gitk
- GPL
- Gtk
- gui
- HasReadOnlyMode
- HBox
- hostnames
- HOWTO
- http
- IBS
- idmapd
- inetd
- INETD
- Initrd
- instserver
- instsys
- IP
- IPL
- iplb
- irb
- iscsi
- iSCSI
- isns
- iSNS
- IUCV
- journalctl
- jpeg
- KDE
- kdump
- Kerberos
- Kobliha's
- KVM
- Ladislav's
- laf
- LangAddOn
- ldap
- ldapcpplib
- LGPL
- LGTM
- libstorage
- liby
- libycp
- libyui
- libYUI
- Linuxrc
- Linux's
- lio
- LIO
- localhost
- logfile
- login
- logrotate
- LTS
- lxc
- LXC
- mailinglist
- Makefile
- MAXLOGNUM
- MAXLOGSIZE
- metadata
- metapackage
- mkdocs
- MkDocs
- MODETEST
- ModuleType
- multipath
- namespace
- navbar
- ncurses
- Ncurses
- needinfo
- NEEDINFO
- nfs
- Nfs
- NfsAutoClient
- NG
- nis
- ntp
- NTP
- nux's p
- NVRA
- ok
- oneline
- online
- Online
- ons
- openQA
- OpenSLP
- opensuse
- openwsman
- operatingSystem
- oscrc
- PackagesProposal
- pam
- param
- PARSECOMMENTS
- partitioner
- perl
- plugin
- png
- pos
- POS
- POV
- profiler
- PROFILER
- Prolog
- PulseAudio
- PushButton
- PyYAML
- qf
- rdp
- RDP
- readdir
- README
- readthedocs
- ReaR
- RECURSIONLIMIT
- refactoring
- Refactoring
- reipl
- reiterate
- renderer
- REPL
- REQ
- ret
- rnc
- RootOnly
- RPMs
- RPMS
- rspec
- RuboCop
- Rubydoc
- rubygem
- rubygems
- runtime
- sbin
- SCC
- scr
- SCRClose
- scrconf
- screenshot
- ScriptingAgent
- SCRNOSORT
- SCROpen
- SCRSetDefault
- SCRSWEEP
- sda
- SetDesktopIcon
- SetModified
- SHA
- SHAs
- simplecov
- skelcd
- SLE
- SLES
- slp
- SMB
- SMT
- snapshotting
- SoftwareApplication
- SortKey
- SOURCERPM
- sr
- src
- SSSD
- startshell
- ST L
- stylesheets
- subcomponents
- supportconfig
- SuSE
- SUSE
- SUSE's
- sys
- sysconfig
- TCL
- textdomain
- tftp
- TFTP
- TimezoneSelector
- tmp
- toolchain
- toplevel
- travis
- Trello
- tui
- ui
- understandability
- url
- USB
- usr
- VBox
- Veewee
- versa
- virtualization
- vm
- VM
- vsftpd
- wfm
- wiki
- Wiki
- WIP
- Workflow
- WriteOnly
- xdg
- XEN
- xinetd
- xml
- XREFDEBUG
- xsl
- Yast
- YAST
- YP
- ytrello
- YYDEBUG
- ZFCP
- zSeries
