---
dictionary:
- Apparmor
- AutoYaST
- Autotools
- Bootloader
- Btrfs
- Builtins
- CIFS
- CIM
- CLI
- Changelog
- DASD
- DBus
- DNS
- FCoE
- FTPd
- Fibre
- FileSystem
- GCC
- Gtk
- GPL
- Github
- HOWTO
- IBS
- IP
- IPL
- IUCV
- KVM
- Kerberos
- Kobliha's
- LGPL
- LGTM
- LIO
- LTS
- LXC
- Ladislav's
- LangAddOn
- Linux's
- Linuxrc
- Makefile
- MkDocs
- NTP
- NVRA
- Ncurses
- Online
- OpenSLP
- POS
- POV
- Prolog
- PulseAudio
- PushButton
- PyYAML
- RDP
- README
- REQ
- RPMS
- ReaR
- Refactoring
- RuboCop
- Rubydoc
- SCC
- SCRClose
- SCROpen
- SCRSetDefault
- SLE
- SMB
- SMT
- SOURCERPM
- SSSD
- ST L
- SUSE's
- SoftwareApplication
- TCL
- TFTP
- USB
- VBox
- Veewee
- Wiki
- WIP
- Workflow
- XEN
- YP
- Yast
- ZFCP
- abovementioned
- afterwards
- apparmor
- aspell
- auth
- autoconf
- autoconfiguration
- autoinstallation
- autolinking
- automake
- autotools
- autoyast
- backport
- backporting
- bootloader
- bugzilla
- cd
- cheatsheet
- chroot
- chrooted
- cim
- cio
- cmdline
- conf
- cvs
- dbus
- debian
- desc
- devtools
- dhcp
- dir
- dns
- docbook
- drbd
- endfor
- endif
- fcoe
- firstboot
- fontconfig
- gcc
- geo
- gitk
- hostnames
- http
- iSCSI
- iSNS
- idmapd
- inetd
- instserver
- iplb
- iscsi
- isns
- journalctl
- kdump
- laf
- ldap
- ldapcpplib
- libYUI
- libstorage
- liby
- libycp
- libyui
- lio
- login
- lxc
- mailinglist
- metadata
- metapackage
- mkdocs
- multipath
- namespace
- navbar
- ncurses
- NEEDINFO
- needinfo
- nfs
- nis
- ntp
- nux's p
- oneline
- online
- ons
- openQA
- opensuse
- openwsman
- operatingSystem
- pam
- partitioner
- perl
- plugin
- png
- pos
- qf
- rdp
- readthedocs
- refactoring
- reipl
- renderer
- rspec
- rubygem
- rubygems
- scr
- scrconf
- screenshot
- simplecov
- skelcd
- slp
- snapshotting
- sr
- startshell
- stylesheets
- subcomponents
- sys
- sysconfig
- tftp
- tmp
- toolchain
- travis
- Trello
- ui
- understandability
- url
- usr
- versa
- virtualization
- vm
- vsftpd
- wfm
- wiki
- xdg
- xinetd
- xml
- xsl
- ytrello
- zSeries
