
# no need for sudo, use the container based build for faster boot
sudo: false

language: ruby
rvm:
  - 2.5

addons:
  apt:
    packages:
    - libaspell-dev
    - aspell-en

env:
  # nokogiri speed up: use the system libxml2, do not compile the bundled version
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=1

before_install:
  - npm install surge

script:
  - bundle exec rake
  - bundle exec jekyll build
  - bundle exec ./.travis_deploy.rb

